DROP TABLE HIREDATEDIM;
DROP TABLE SALESDATEDIM;
DROP TABLE SEASONDIM;
DROP TABLE CUSTOMERTYPEDIM;
DROP TABLE CATEGORYDIM;
DROP TABLE BRANCHDIM;
DROP TABLE SALESSCALEDIM;
DROP TABLE HIRETEMPFACT;
DROP TABLE HIREFACT;
DROP TABLE SALESTEMPFACT;
DROP TABLE SALESFACT;

------------------------------------------------------------------------------------------------------
-- CREATING DIMENSION TABLES
------------------------------------------------------------------------------------------------------

-- CREATE THE HIRE DATE DIMENSION, CONCATENATING YEAR AND MONTH INTO A UNIQUE HIREDATEID
CREATE TABLE HIREDATEDIM
AS SELECT DISTINCT
    TO_CHAR(START_DATE, 'YYYYMM') AS HIREDATEID,
    TO_CHAR(START_DATE, 'YYYY') AS YEAR,
    TO_CHAR(START_DATE, 'MM') AS MONTH
FROM HIRE;

-- CREATE THE SALES DATE DIMENSION, CONCATENATING YEAR AND MONTH INTO A UNIQUE SALESDATEID
CREATE TABLE SALESDATEDIM
AS SELECT DISTINCT
    TO_CHAR(SALES_DATE, 'YYYYMM') AS SALESDATEID,
    TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
    TO_CHAR(SALES_DATE, 'MM') AS MONTH
FROM SALES;

-- CREATE THE SEASON DIMENSION, ALLOWING US TO LATER SORT MONTHS INTO THE SEASON THEY FALL INTO
CREATE TABLE SEASONDIM
    (SEASONID    VARCHAR2(6) NOT NULL,
    SEASONDESC   VARCHAR2(7) NOT NULL);

-- SORT MONTHS INTO THE SEASON THEY FALL INTO    
INSERT INTO SEASONDIM VALUES ('SUMMER','DEC-FEB');
INSERT INTO SEASONDIM VALUES ('AUTUMN','MAR-MAY');
INSERT INTO SEASONDIM VALUES ('WINTER','JUN-AUG');
INSERT INTO SEASONDIM VALUES ('SPRING','SEP-NOV');

-- CREATE THE CUSTOMER TYPE DIMENSION, USING CUSTOMERTYPE.CUSTOMER_TYPE_ID AS A UNIQUE IDENTIFIER
CREATE TABLE CUSTOMERTYPEDIM
AS SELECT DESCRIPTION
FROM CUSTOMER_TYPE;

-- CREATE THE EQUIPMENT CATEGORY DIMENSION, USING CATEGORY.CATEGORY_DESCRIPTION AS A UNIQUE IDENTIFIER
CREATE TABLE CATEGORYDIM
AS SELECT CATEGORY_DESCRIPTION
FROM CATEGORY;

-- CREATE THE COMPANY BRANCH DIMENSION, USING STAFF.COMPANY_BRANCH AS A UNIQUE IDENTIFIER
CREATE TABLE BRANCHDIM
AS SELECT DISTINCT COMPANY_BRANCH
FROM STAFF;

-- CREATE THE SALES SCALE DIMENSION, ALLOWING US TO LATER SORT SALES AMOUNTS INTO THE CATEGORY THEY FALL INTO
CREATE TABLE SALESSCALEDIM
    (SALESSCALEID   VARCHAR2(6)  NOT NULL,
    SALESSCALEDESC  VARCHAR2(26)  NOT NULL);

-- SORT SALES AMOUNTS INTO THE CATEGORY THEY FALL INTO
INSERT INTO SALESSCALEDIM VALUES ('LOW','<$5,000');
INSERT INTO SALESSCALEDIM VALUES ('MEDIUM','BETWEEN $5,000 AND $10,000');
INSERT INTO SALESSCALEDIM VALUES ('HIGH','>$10,000');


------------------------------------------------------------------------------------------------------
-- CREATING FACT TABLES
------------------------------------------------------------------------------------------------------

-- [HIRE] CREATE A TEMPORARY FACT TABLE TO ALLOW US TO INSERT THE CALCULATED SEASON DIMENSION
CREATE TABLE HIRETEMPFACT
AS SELECT
	HIRE.START_DATE AS HIRE_DATE,
	CUSTOMER_TYPE.DESCRIPTION AS CUSTOMER_TYPE,
	CATEGORY.CATEGORY_DESCRIPTION AS EQUIPMENT_CATEGORY,
	STAFF.COMPANY_BRANCH,
    HIRE.TOTAL_HIRE_PRICE,
    HIRE.QUANTITY
FROM HIRE,CUSTOMER,EQUIPMENT,STAFF,CATEGORY,CUSTOMER_TYPE
WHERE HIRE.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
AND HIRE.EQUIPMENT_ID = EQUIPMENT.EQUIPMENT_ID
AND HIRE.STAFF_ID = STAFF.STAFF_ID
AND EQUIPMENT.CATEGORY_ID = CATEGORY.CATEGORY_ID
AND CUSTOMER.CUSTOMER_TYPE_ID = CUSTOMER_TYPE.CUSTOMER_TYPE_ID
ORDER BY HIRE.START_DATE;

-- [HIRE] UPDATE THE TABLE TO INCLUDE THE SEASON DIMENSION BASED ON THE INCLUDED HIRE_DATE
ALTER TABLE HIRETEMPFACT
ADD (SEASON VARCHAR2(6));

UPDATE HIRETEMPFACT
SET SEASON = 'SUMMER'
WHERE TO_CHAR(HIRE_DATE, 'MON') IN ('DEC','JAN','FEB');

UPDATE HIRETEMPFACT
SET SEASON = 'AUTUMN'
WHERE TO_CHAR(HIRE_DATE, 'MON') IN ('MAR','APR','MAY');

UPDATE HIRETEMPFACT
SET SEASON = 'WINTER'
WHERE TO_CHAR(HIRE_DATE, 'MON') IN ('JUN','JUL','AUG');

UPDATE HIRETEMPFACT
SET SEASON = 'SPRING'
WHERE TO_CHAR(HIRE_DATE, 'MON') IN ('SEP','OCT','NOV');

-- [HIRE] GENERATE A FINAL FACT TABLE FOR HIRE
CREATE TABLE HIREFACT
AS SELECT
    TO_CHAR(HIRE_DATE,'YYYYMM') AS DATE_ID,
    SEASON,
    CUSTOMER_TYPE,
    EQUIPMENT_CATEGORY,
    COMPANY_BRANCH,
    SUM(TOTAL_HIRE_PRICE) AS TOTAL_HIRE_PRICE,
    SUM(QUANTITY) AS QUANTITY
FROM HIRETEMPFACT
GROUP BY SEASON, CUSTOMER_TYPE, COMPANY_BRANCH, TO_CHAR(HIRE_DATE,'YYYYMM'), EQUIPMENT_CATEGORY;


-- [SALES] CREATE A TEMPORARY FACT TABLE TO ALLOW US TO INSERT THE CALCULATED SEASON DIMENSION
CREATE TABLE SALESTEMPFACT
AS SELECT
	SALES.SALES_DATE AS SALE_DATE,
	CUSTOMER_TYPE.DESCRIPTION AS CUSTOMER_TYPE,
	CATEGORY.CATEGORY_DESCRIPTION AS EQUIPMENT_CATEGORY,
	STAFF.COMPANY_BRANCH,
    SALES.TOTAL_SALES_PRICE,
    SALES.QUANTITY
FROM SALES,CUSTOMER,EQUIPMENT,STAFF,CATEGORY,CUSTOMER_TYPE
WHERE SALES.CUSTOMER_ID = CUSTOMER.CUSTOMER_ID
AND SALES.EQUIPMENT_ID = EQUIPMENT.EQUIPMENT_ID
AND SALES.STAFF_ID = STAFF.STAFF_ID
AND EQUIPMENT.CATEGORY_ID = CATEGORY.CATEGORY_ID
AND CUSTOMER.CUSTOMER_TYPE_ID = CUSTOMER_TYPE.CUSTOMER_TYPE_ID
ORDER BY SALES.SALES_DATE;

-- [SALES] UPDATE THE TABLE TO INCLUDE THE SEASON DIMENSION BASED ON THE INCLUDED SALE_DATE
-- [SALES] UPDATE THE TABLE TO INCLUDE THE SALES PRICE SCALE DIMENSION BASED ON THE INCLUDED TOTAL_SALES_PRICE
ALTER TABLE SALESTEMPFACT
ADD (SEASON VARCHAR2(6),
SALES_PRICE_SCALE  VARCHAR2(6));

UPDATE SALESTEMPFACT
SET SEASON = 'SUMMER'
WHERE TO_CHAR(SALE_DATE, 'MON') IN ('DEC','JAN','FEB');

UPDATE SALESTEMPFACT
SET SEASON = 'AUTUMN'
WHERE TO_CHAR(SALE_DATE, 'MON') IN ('MAR','APR','MAY');

UPDATE SALESTEMPFACT
SET SEASON = 'WINTER'
WHERE TO_CHAR(SALE_DATE, 'MON') IN ('JUN','JUL','AUG');

UPDATE SALESTEMPFACT
SET SEASON = 'SPRING'
WHERE TO_CHAR(SALE_DATE, 'MON') IN ('SEP','OCT','NOV');

UPDATE SALESTEMPFACT
SET SALES_PRICE_SCALE = 'LOW'
WHERE TOTAL_SALES_PRICE <=5000;

UPDATE SALESTEMPFACT
SET SALES_PRICE_SCALE = 'MEDIUM'
WHERE TOTAL_SALES_PRICE >5000
AND TOTAL_SALES_PRICE<10000;

UPDATE SALESTEMPFACT
SET SALES_PRICE_SCALE = 'HIGH'
WHERE TOTAL_SALES_PRICE>=10000;

-- [SALES] GENERATE A FINAL FACT TABLE FOR SALES
CREATE TABLE SALESFACT
AS SELECT
    TO_CHAR(SALE_DATE,'YYYYMM') AS DATE_ID,
    SEASON,
    CUSTOMER_TYPE,
    EQUIPMENT_CATEGORY,
    COMPANY_BRANCH,
    SALES_PRICE_SCALE,
    SUM(TOTAL_SALES_PRICE) AS TOTAL_SALES,
    SUM(QUANTITY) AS QUANTITY
FROM SALESTEMPFACT
GROUP BY SEASON, CUSTOMER_TYPE, COMPANY_BRANCH, TO_CHAR(SALE_DATE,'YYYYMM'), SALES_PRICE_SCALE,EQUIPMENT_CATEGORY;