-- REPORT 1
SELECT * FROM 
    (SELECT SEASON, CUSTOMER_TYPE, SUM(TOTAL_HIRE_PRICE) AS HIRE_REVENUE,
    RANK() OVER (ORDER BY SUM(TOTAL_HIRE_PRICE) DESC) AS HIRE_RANK
    FROM HIREFACT
    GROUP BY SEASON, CUSTOMER_TYPE)
WHERE HIRE_RANK < 26;

-- REPORT 2
SELECT * FROM
    (SELECT EQUIPMENT_CATEGORY, COMPANY_BRANCH, SUM(TOTAL_SALES) AS SALES_REVENUE,
    ROUND(PERCENT_RANK() OVER (ORDER BY SUM(TOTAL_SALES)),2) AS SALES_PERCENTILE
    FROM SALESFACT
    GROUP BY EQUIPMENT_CATEGORY, COMPANY_BRANCH)
WHERE SALES_PERCENTILE > 0.26;

-- REPORT 3
SELECT 
    DECODE(GROUPING(COMPANY_BRANCH),1,'ALL BRANCHES',COMPANY_BRANCH) AS BRANCH,
    DECODE(GROUPING(CUSTOMER_TYPE),1,'ALL CUSTOMERS',CUSTOMER_TYPE) AS CUSTOMER,
    DECODE(GROUPING(TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON')),1,'ALL MONTHS', TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON')) AS MONTH,
SUM(TOTAL_SALES)
FROM SALESFACT
GROUP BY CUBE (COMPANY_BRANCH, CUSTOMER_TYPE,TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'))
ORDER BY COMPANY_BRANCH,CUSTOMER_TYPE,TO_DATE(TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'),'MON');

-- REPORT 4
SELECT 
    DECODE(GROUPING(COMPANY_BRANCH),1,'ALL BRANCHES',COMPANY_BRANCH) AS BRANCH,
    DECODE(GROUPING(CUSTOMER_TYPE),1,'ALL CUSTOMERS',CUSTOMER_TYPE) AS CUSTOMER,
    DECODE(GROUPING(TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON')),1,'ALL MONTHS', TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON')) AS MONTH,
SUM(TOTAL_SALES)
FROM SALESFACT
GROUP BY COMPANY_BRANCH, CUBE(CUSTOMER_TYPE,TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'))
ORDER BY COMPANY_BRANCH,CUSTOMER_TYPE,TO_DATE(TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'),'MON');

-- REPORT 5
SELECT 
    DECODE(GROUPING(EQUIPMENT_CATEGORY),1,'ALL CATEGORIES',EQUIPMENT_CATEGORY) AS EQUIPMENT_CATEGORY,
    DECODE(GROUPING(CUSTOMER_TYPE),1,'ALL CUSTOMERS',CUSTOMER_TYPE) AS CUSTOMER,
    DECODE(GROUPING(SEASON),1,'ALL SEASONS',SEASON) AS SEASON,
SUM(TOTAL_SALES)
FROM SALESFACT
GROUP BY ROLLUP (EQUIPMENT_CATEGORY, CUSTOMER_TYPE, SEASON)
ORDER BY EQUIPMENT_CATEGORY,CUSTOMER_TYPE,SEASON;

-- REPORT 6
SELECT 
    DECODE(GROUPING(EQUIPMENT_CATEGORY),1,'ALL EQUIPMENT CATEGORIES',EQUIPMENT_CATEGORY) AS EQUIPMENT_CATEGORY,
    DECODE(GROUPING(CUSTOMER_TYPE),1,'ALL CUSTOMERS',CUSTOMER_TYPE) AS CUSTOMER,
    DECODE(GROUPING(SEASON),1,'ALL SEASONS',SEASON) AS SEASON,
SUM(TOTAL_SALES)
FROM SALESFACT
GROUP BY EQUIPMENT_CATEGORY, ROLLUP (CUSTOMER_TYPE, SEASON)
ORDER BY EQUIPMENT_CATEGORY,CUSTOMER_TYPE,SEASON;
 
-- REPORT 7
SELECT TO_CHAR(TO_DATE(YEAR,'YYYY'),'YYYY'),
SUM(TOTAL_HIRE_PRICE) as TOTAL_HIRE_PRICE,
SUM(SUM(TOTAL_HIRE_PRICE))
    OVER (ORDER BY TO_CHAR(TO_DATE(YEAR,'YYYY'),'YYYY') ROWS UNBOUNDED PRECEDING) AS CUMULATIVE_HIRE_PRICE
FROM HIREFACT,HIREDATEDIM
WHERE HIREFACT.DATE_ID=HIREDATEDIM.HIREDATEID
AND HIREFACT.EQUIPMENT_CATEGORY='Site Equipment'
GROUP BY TO_CHAR(TO_DATE(YEAR,'YYYY'),'YYYY');

-- REPORT 8
SELECT SALESFACT.EQUIPMENT_CATEGORY,SALESDATEDIM.YEAR,SALESDATEDIM.MONTH,SALESFACT.TOTAL_SALES,
ROUND(AVG(SUM(SALESFACT.TOTAL_SALES))
    OVER (ORDER BY EQUIPMENT_CATEGORY,SALESDATEDIM.YEAR,SALESDATEDIM.MONTH ROWS 5 PRECEDING),2) AS AVG_SALES
FROM SALESFACT JOIN SALESDATEDIM
ON SALESFACT.DATE_ID=SALESDATEDIM.SALESDATEID
GROUP BY SALESFACT.EQUIPMENT_CATEGORY,SALESDATEDIM.YEAR,SALESDATEDIM.MONTH,SALESFACT.TOTAL_SALES
ORDER BY SALESFACT.EQUIPMENT_CATEGORY,SALESDATEDIM.YEAR,SALESDATEDIM.MONTH;

-- REPORT 9
SELECT HIREFACT.EQUIPMENT_CATEGORY,TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'),HIREFACT.COMPANY_BRANCH,SUM(TOTAL_HIRE_PRICE),
    DENSE_RANK() OVER (PARTITION BY TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON')
        ORDER BY SUM(TOTAL_HIRE_PRICE) DESC) AS RANK_BY_MONTH,
    DENSE_RANK() OVER (PARTITION BY HIREFACT.COMPANY_BRANCH
        ORDER BY SUM(TOTAL_HIRE_PRICE) DESC) AS RANK_BY_BRANCH
FROM HIREFACT,HIREDATEDIM
WHERE HIREFACT.DATE_ID=HIREDATEDIM.HIREDATEID
GROUP BY HIREFACT.EQUIPMENT_CATEGORY,TO_CHAR(TO_DATE(DATE_ID,'YYYYMM'),'MON'),HIREFACT.COMPANY_BRANCH;